

name: Deploy Project App


on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: installing necessary dependencies
        run: npm ci
      
      - name: building the app
        run: npm run build


      - name: Debug Vercel secrets
        run: |
          echo "Vercel Token: ${{ secrets.VERCEL_TOKEN }}"
          echo "Vercel Org ID: ${{ secrets.VERCEL_ORG_ID }}"
          echo "Vercel Project ID: ${{ secrets.VERCEL_PROJECT_ID }}"


      - name: deploy the project on Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--yes"
          working-directory: . 
      
      

        
